# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Minecraft2D.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Minecraft2D(object):
    def setupUi(self, Minecraft2D):
        Minecraft2D.setObjectName("Minecraft2D")
        Minecraft2D.resize(1000, 618)
        Minecraft2D.setStyleSheet("QPushButton{\n"
"    border-image: url(:/gui/res/gui/default.png);\n"
"}\n"
"QPushButton:hover{\n"
"    border-image: url(:/gui/res/gui/hover.png);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-image: url(:/gui/res/gui/pressed.png);\n"
"}\n"
"QWidget#p_main{\n"
"    border-image: url(:/gui/res/gui/cover.png);\n"
"}")
        self.p_main = QtWidgets.QWidget()
        self.p_main.setObjectName("p_main")
        self.label_logo = QtWidgets.QLabel(self.p_main)
        self.label_logo.setGeometry(QtCore.QRect(250, 0, 500, 150))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap(":/gui/res/gui/logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.pb_singleplayer = QtWidgets.QPushButton(self.p_main)
        self.pb_singleplayer.setGeometry(QtCore.QRect(250, 200, 500, 25))
        self.pb_singleplayer.setObjectName("pb_singleplayer")
        Minecraft2D.addWidget(self.p_main)
        self.p_singleplayer = QtWidgets.QWidget()
        self.p_singleplayer.setObjectName("p_singleplayer")
        self.gridLayout = QtWidgets.QGridLayout(self.p_singleplayer)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_startgame = QtWidgets.QPushButton(self.p_singleplayer)
        self.pb_startgame.setEnabled(False)
        self.pb_startgame.setObjectName("pb_startgame")
        self.gridLayout.addWidget(self.pb_startgame, 1, 1, 1, 1)
        self.pb_back = QtWidgets.QPushButton(self.p_singleplayer)
        self.pb_back.setObjectName("pb_back")
        self.gridLayout.addWidget(self.pb_back, 1, 4, 1, 1)
        self.lw_saves = QtWidgets.QListWidget(self.p_singleplayer)
        self.lw_saves.setObjectName("lw_saves")
        self.gridLayout.addWidget(self.lw_saves, 0, 0, 1, 5)
        self.pb_edit = QtWidgets.QPushButton(self.p_singleplayer)
        self.pb_edit.setEnabled(False)
        self.pb_edit.setObjectName("pb_edit")
        self.gridLayout.addWidget(self.pb_edit, 1, 2, 1, 1)
        self.pb_new = QtWidgets.QPushButton(self.p_singleplayer)
        self.pb_new.setObjectName("pb_new")
        self.gridLayout.addWidget(self.pb_new, 1, 0, 1, 1)
        self.pb_del = QtWidgets.QPushButton(self.p_singleplayer)
        self.pb_del.setEnabled(False)
        self.pb_del.setObjectName("pb_del")
        self.gridLayout.addWidget(self.pb_del, 1, 3, 1, 1)
        Minecraft2D.addWidget(self.p_singleplayer)
        self.p_new = QtWidgets.QWidget()
        self.p_new.setObjectName("p_new")
        self.le_savename = QtWidgets.QLineEdit(self.p_new)
        self.le_savename.setGeometry(QtCore.QRect(372, 277, 256, 32))
        self.le_savename.setObjectName("le_savename")
        self.pb_create = QtWidgets.QPushButton(self.p_new)
        self.pb_create.setGeometry(QtCore.QRect(372, 309, 128, 32))
        self.pb_create.setObjectName("pb_create")
        self.pb_cancel = QtWidgets.QPushButton(self.p_new)
        self.pb_cancel.setGeometry(QtCore.QRect(500, 309, 128, 32))
        self.pb_cancel.setObjectName("pb_cancel")
        Minecraft2D.addWidget(self.p_new)
        self.p_del = QtWidgets.QWidget()
        self.p_del.setObjectName("p_del")
        self.label_info = QtWidgets.QLabel(self.p_del)
        self.label_info.setGeometry(QtCore.QRect(372, 277, 256, 32))
        self.label_info.setObjectName("label_info")
        self.pb_yes = QtWidgets.QPushButton(self.p_del)
        self.pb_yes.setGeometry(QtCore.QRect(372, 309, 128, 32))
        self.pb_yes.setObjectName("pb_yes")
        self.pb_no = QtWidgets.QPushButton(self.p_del)
        self.pb_no.setGeometry(QtCore.QRect(500, 309, 128, 32))
        self.pb_no.setObjectName("pb_no")
        Minecraft2D.addWidget(self.p_del)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_name = QtWidgets.QLineEdit(self.page)
        self.le_name.setObjectName("le_name")
        self.gridLayout_2.addWidget(self.le_name, 0, 1, 1, 1)
        self.pb_openfoder = QtWidgets.QPushButton(self.page)
        self.pb_openfoder.setObjectName("pb_openfoder")
        self.gridLayout_2.addWidget(self.pb_openfoder, 1, 1, 1, 1)
        self.pb_done = QtWidgets.QPushButton(self.page)
        self.pb_done.setObjectName("pb_done")
        self.gridLayout_2.addWidget(self.pb_done, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        Minecraft2D.addWidget(self.page)

        self.retranslateUi(Minecraft2D)
        QtCore.QMetaObject.connectSlotsByName(Minecraft2D)

    def retranslateUi(self, Minecraft2D):
        _translate = QtCore.QCoreApplication.translate
        Minecraft2D.setWindowTitle(_translate("Minecraft2D", "Minecraft2D"))
        self.pb_singleplayer.setText(_translate("Minecraft2D", "单人游戏"))
        self.pb_startgame.setText(_translate("Minecraft2D", "开始游戏"))
        self.pb_back.setText(_translate("Minecraft2D", "返回"))
        self.pb_edit.setText(_translate("Minecraft2D", "编辑"))
        self.pb_new.setText(_translate("Minecraft2D", "新游戏"))
        self.pb_del.setText(_translate("Minecraft2D", "删除"))
        self.le_savename.setPlaceholderText(_translate("Minecraft2D", "输入存档名称"))
        self.pb_create.setText(_translate("Minecraft2D", "创建"))
        self.pb_cancel.setText(_translate("Minecraft2D", "取消"))
        self.label_info.setText(_translate("Minecraft2D", "确定删除?"))
        self.pb_yes.setText(_translate("Minecraft2D", "是"))
        self.pb_no.setText(_translate("Minecraft2D", "否"))
        self.pb_openfoder.setText(_translate("Minecraft2D", "打开文件夹"))
        self.pb_done.setText(_translate("Minecraft2D", "完成"))
import Minecraft2D_rc
